-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 23:44:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema techgame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techgame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techgame` DEFAULT CHARACTER SET utf8 ;
USE `techgame` ;

-- -----------------------------------------------------
-- Table `techgame`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techgame`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `techgame`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techgame`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `category_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_brands_categories_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_brands_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `techgame`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `techgame`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techgame`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `sku` INT NOT NULL,
  `stock` INT NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `discount` INT NULL DEFAULT NULL,
  `brand_id` INT NOT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `brands_brand_id_foreign_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `brands_brand_id_foreign`
    FOREIGN KEY (`brand_id`)
    REFERENCES `techgame`.`brands` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `techgame`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techgame`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `techgame`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techgame`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_roles_users_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_users`
    FOREIGN KEY (`rol_id`)
    REFERENCES `techgame`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `techgame`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techgame`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `products_id_foreign_idx` (`product_id` ASC) VISIBLE,
  INDEX `users_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `products_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `techgame`.`products` (`id`),
  CONSTRAINT `users_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `techgame`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `techgame`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techgame`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_id_foreign_idx` (`user_id` ASC) VISIBLE,
  INDEX `products_id_foreign_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `techgame`.`products` (`id`),
  CONSTRAINT `users_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `techgame`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
